spring.application.name=movie
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
logging.level.org.springframework.web.servlet=DEBUG
spring.thymeleaf.cache=false